import { ProjectData } from '../types';
import botnixLogoImage from '../assets/images/botnix_logo_1788793085484.jpg';
import robotHeroImage from '../assets/images/borehole_rescue_robot_1788792274094.jpg';
import groundUnitImage from '../assets/images/ground_control_unit_1788793117708.jpg';
import fabricationImage from '../assets/images/robot_fabrication_1788792297653.jpg';

export const INITIAL_PROJECT_DATA: ProjectData = {
  name: "BOTNIX - Borewell Rescue Robot",
  projectCode: "BOTNIX",
  motto: "RESCUE. REACH. SAVE.",
  subtitle: "Dual-Unit Borewell Life-Saving Robotic System with RS-485 Ethernet Umbilical, Chest Grab Claw & 2-Motor Foldable Base Support",
  team: {
    name: "Team BOTNIX",
    members: ["Lead Robotics Engineer", "Electronics & C++ Programmer", "Mechanical Design Lead"],
    institution: "Bangladesh Robotics & Innovation Forum",
    competitionEvent: "International Robotics Championship",
    competitionRound: "International Grand Finals - Malaysia",
    countryTarget: "Kuala Lumpur, Malaysia",
    originCountry: "Bangladesh 2026",
    year: "2026",
  },
  overallCondition: {
    readinessStatus: "Competition Ready - Malaysia Finals",
    depthRatingMeters: 40,
    boreholeDiameterRange: "150 mm – 350 mm (6\" to 14\" borewells)",
    payloadCapacityKg: 25,
    totalWeightKg: 5.4,
    batterySpec: "12V 8Ah High-Discharge Battery",
    batteryBackupMinutes: 25,
    microcontroller: "Arduino Mega (ATmega2560)",
    firmwareLanguage: "C++ (Embedded Control Architecture)",
    motorCount: 4,
    relayModule: "8-Channel Relay Module (2 Relays per Motor for Forward/Backward H-Bridge Control)",
    communicationProtocol: "RS-485 Industrial Differential Serial (MAX485 Transceiver)",
    tetherCableType: "Standard 8-Core Shielded Ethernet Cable (Cat5e / Cat6 Twisted Pair)",
    liftingMechanism: "Manual Hand Pulley Lowering & High-Tensile Tether Line",
    voiceCommunication: "One-Way Audio Comm (Surface-to-Borewell Speaker for reassuring victim)",
    oxygenDelivery: "Medical Grade Oxygen/Fresh Air Conduit Tube",
    cameraSpecs: "Wide-Angle Low-Light Inspection Camera with Ultra-Bright LED Ring",
    subsystems: [
      {
        id: "sub-1",
        name: "Main Chest Gripping Claw",
        category: "mechanical",
        status: "Operational",
        healthPercentage: 98,
        detail: "DC motor driven mechanical claw engineered to gently and firmly grab the child's chest.",
      },
      {
        id: "sub-2",
        name: "Extra Foldable Base Leg Support",
        category: "mechanical",
        status: "Operational",
        healthPercentage: 95,
        detail: "Dual-motor folding mechanism that deploys beneath the child's legs/feet to provide bottom base support.",
      },
      {
        id: "sub-3",
        name: "RS-485 Long-Distance Serial Link (Ethernet Cable)",
        category: "telecom",
        status: "Operational",
        healthPercentage: 99,
        detail: "Differential pair communication over 8-core Cat5e Ethernet cable connecting Ground Unit to downhole Robot Unit with high EMI noise immunity.",
      },
      {
        id: "sub-4",
        name: "8-Channel Relay & 4 DC Motor Drive",
        category: "electrical",
        status: "Operational",
        healthPercentage: 100,
        detail: "8 relays configured in pairs: each motor has 1 relay for forward movement and 1 relay for backward movement.",
      },
      {
        id: "sub-5",
        name: "Ground Unit Real-Time Status Display",
        category: "electrical",
        status: "Operational",
        healthPercentage: 97,
        detail: "Surface LCD screen displaying real-time running states (Motor 1, 2, 3, 4 Forward/Backward/Stop).",
      },
      {
        id: "sub-6",
        name: "Inspection Camera & One-Way Voice System",
        category: "optical",
        status: "Operational",
        healthPercentage: 94,
        detail: "Real-time downhole video feed with surface-to-child voice link to calm the trapped victim.",
      },
      {
        id: "sub-7",
        name: "12V 8Ah Power & Oxygen Life Support",
        category: "pneumatic",
        status: "Operational",
        healthPercentage: 96,
        detail: "Dedicated 12V 8Ah battery delivering 20–30 min runtime with continuous oxygen tube feed.",
      },
    ],
  },
  units: {
    robotUnit: {
      title: "The In-Borewell Robot Unit",
      description: "The compact cylindrical robotic apparatus lowered into the narrow vertical borewell. Designed to navigate deep underground distances, locate the child, supply air, speak, and mechanically secure the victim.",
      mainClaw: "Main Chest Claw: Powered by a high-torque DC motor through an 8-relay controller (forward grips chest, backward opens).",
      foldableSupport: "Foldable Base Support: Compactly folded during shaft descent. Once reaching beneath the child's legs, 2 dedicated motors unfold the support arms to hold the child safely from the bottom.",
      cameraSystem: "Downward-facing illuminated inspection camera transmitting visual confirmation to the ground operator.",
      voiceMethod: "One-Way Audio Communication: Rescuer voice transmitted down through a borehole speaker to soothe the child.",
      oxygenLine: "Direct life-support conduit pumping fresh oxygen/air down the borewell shaft.",
      liftingMethod: "Suspended and maneuvered up/down manually by hand or tether line for responsive tactile feedback.",
      motorAssignment: "4 DC Motors total (Claw motor, 2 Foldable Support motors, Auxiliary drive).",
      communicationNode: "Downhole RS-485 transceiver (MAX485) receiving motor commands from the surface and transmitting telemetry up through the Cat5e Ethernet cable.",
    },
    groundUnit: {
      title: "The Surface Ground Unit (Control Panel)",
      description: "The portable command console stationed at the mouth of the borewell. Communicates over long underground distance via an 8-core Ethernet cable using the industrial RS-485 protocol.",
      controlPanel: "Master control panel with tactile switches and directional toggles to command each individual motor.",
      displaySystem: "Real-Time Digital Display: Instantly visualizes the working status of Motor 1, Motor 2, Motor 3, Motor 4 (Forward, Backward, Stopped) and relay actuation.",
      relayBox: "Houses the 8-Channel Relay Module wired to the Arduino Mega for bidirectional polarity switching.",
      powerSource: "12-Volt 8-Ampere (12V 8Ah) heavy-duty battery supplying reliable 20–30 minute uninterrupted mission power.",
      operatorRole: "Provides the human rescuer with complete visual and mechanical control over the delicate rescue operation.",
      communicationMaster: "Master RS-485 interface transmitting user switch states over Cat5e Ethernet cable down to the submerged robot unit.",
    },
  },
  slots: [
    {
      id: "slot-logo",
      title: "Project & Team Logo (BOTNIX)",
      shortDescription: "Official team insignia with 'BOTNIX BOREWELL RESCUE ROBOT - BANGLADESH 2026' crest.",
      category: "logo",
      url: botnixLogoImage,
      caption: "BOTNIX Team Crest: 'Rescue. Reach. Save.' - Representing Bangladesh at Malaysia International Round 2026.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-robot-unit",
      title: "Robot Unit (In-Borewell Mechanism)",
      shortDescription: "The cylindrical chassis with main chest grab claw, camera, and foldable base support.",
      category: "robot-unit",
      url: robotHeroImage,
      caption: "Assembled Robot Unit showing cylindrical frame, main claw linkage, and LED camera ring.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-ground-unit",
      title: "Ground Unit (Control Panel & Display)",
      shortDescription: "Surface rescue control station with switches and real-time motor status display screen.",
      category: "ground-unit",
      url: groundUnitImage,
      caption: "Ground Unit control station displaying live status of Motor 1, 2, 3, 4 forward and backward relays.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-rs485-ethernet",
      title: "RS-485 Communication & Ethernet Tether",
      shortDescription: "Industrial RS-485 transceiver (MAX485) and Cat5e 8-core Ethernet cable connecting units over long distances underground.",
      category: "communication",
      url: undefined,
      caption: "RS-485 differential communication module using standard 8-core Ethernet cable for long-distance noise-free telemetry between Ground and Robot units.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-main-claw",
      title: "Main Chest Gripping Claw",
      shortDescription: "The primary DC motor actuated claw designed to grab the child's chest securely.",
      category: "claw",
      url: robotHeroImage,
      caption: "Main chest grab claw assembly driven by high-torque DC motor with dual forward/backward relays.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-base-support",
      title: "Extra Foldable Base Leg Support",
      shortDescription: "Foldable support arms powered by 2 DC motors to deploy underneath the child's legs.",
      category: "base-support",
      url: fabricationImage,
      caption: "Foldable bottom support mechanism: folds during descent and opens under child's feet using 2 motors.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-electronics",
      title: "Arduino Mega & 8-Channel Relay Module",
      shortDescription: "The C++ programmed Arduino Mega board and 8-relay motor switching circuitry.",
      category: "electronics",
      url: fabricationImage,
      caption: "Arduino Mega microcontroller and 8-relay H-bridge module wiring harness for 4 DC motors.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-battery",
      title: "12V 8Ah Power Supply Unit",
      shortDescription: "12-volt 8-ampere battery delivering 20 to 30 minutes of mission backup power.",
      category: "battery",
      url: undefined,
      caption: "12V 8Ah rechargeable battery pack with fuse protection and voltage monitoring.",
      dateUpdated: "2026-03-01",
    },
    {
      id: "slot-camera-audio",
      title: "Camera & One-Way Voice System",
      shortDescription: "Shaft illumination, real-time video, and surface-to-borewell voice communication.",
      category: "custom",
      url: undefined,
      caption: "Inspection camera module with white LED lights and speaker for rescuer voice transmission.",
      dateUpdated: "2026-03-01",
    },
  ],
  photos: [
    {
      id: "photo-logo",
      url: botnixLogoImage,
      title: "BOTNIX - Borewell Rescue Robot Official Logo",
      caption: "Official emblem of Team BOTNIX representing Bangladesh in the International Round Malaysia 2026. Motto: Rescue. Reach. Save.",
      category: "logo",
      dateAdded: "2026-03-01",
      isPrimary: true,
    },
    {
      id: "photo-robot-unit",
      url: robotHeroImage,
      title: "Borewell Robot Unit Prototype",
      caption: "The cylindrical in-borewell vehicle with main chest claw, LED lighting, and guide rollers.",
      category: "robot-unit",
      dateAdded: "2026-03-01",
      isPrimary: false,
    },
    {
      id: "photo-ground-unit",
      url: groundUnitImage,
      title: "Surface Ground Unit Control Station",
      caption: "Operator station with switches and digital real-time display indicating Motor 1, 2, 3, 4 forward and backward status over RS-485.",
      category: "ground-unit",
      dateAdded: "2026-03-01",
      isPrimary: false,
    },
    {
      id: "photo-fabrication",
      url: fabricationImage,
      title: "Arduino Mega & Relay Workbench Assembly",
      caption: "C++ Arduino Mega controller wiring with the 8-channel relay module and RS-485 transceiver bus.",
      category: "electronics",
      dateAdded: "2026-02-20",
      isPrimary: false,
    },
  ],
  fabricationStages: [
    {
      id: "fab-1",
      order: 1,
      title: "Main Chest Gripping Claw & DC Motor Drive",
      phase: "Phase 1: Primary Chest Claw",
      summary: "Fabricated a high-torque mechanical claw capable of securely grabbing the child's chest inside the borewell.",
      materials: [
        "Lightweight aluminum alloy claw fingers",
        "High-torque DC gear motor (12V)",
        "Soft rubber/foam contact padding to protect child's chest",
        "Dual-relay polarity reversal circuitry (Relays 1 & 2)"
      ],
      tools: [
        "Bench drill & metal cutting saw",
        "Torque wrench & caliper",
        "3D printer for custom gear brackets"
      ],
      engineeringProcess: "The main claw was designed to hold the child firmly around the torso without inflicting pain or injury. A high-torque 12V DC motor actuates the mechanical linkages. Two relays from the 8-relay module control this motor: Relay 1 triggers the forward movement (closing and grabbing), while Relay 2 triggers the backward movement (opening and releasing).",
      challengesAndSolutions: "Challenge: Preventing the claw from applying excessive pressure. Solution: Mechanical travel stops and limit switches calibrated to safe gripping limits, with tactile operator override from the ground station.",
      imageUrl: robotHeroImage,
    },
    {
      id: "fab-2",
      order: 2,
      title: "Extra Foldable Base Leg Support Mechanism",
      phase: "Phase 2: Bottom Support Arms",
      summary: "Engineered an auxiliary foldable support system powered by 2 DC motors that opens beneath the child's legs.",
      materials: [
        "Twin folding support arms with pivot hinges",
        "2 dedicated high-torque DC motors",
        "Relays 3, 4, 5, 6 for dual-motor forward/backward actuation",
        "Soft-cushioned bottom foot pads"
      ],
      tools: [
        "TIG welding & aluminum bending press",
        "Linkage testing rig"
      ],
      engineeringProcess: "A major risk in borewell rescue is the victim slipping further down during extraction. To solve this, we created an extra foldable support at the base of the robot. As the robot descends, the support remains folded tight against the chassis to fit the borewell pipe. Once the robot reaches down past the child's legs, the operator turns on the two motors to open and spread the support arms outward, creating a firm bottom platform under the child.",
      challengesAndSolutions: "Challenge: The mechanism must open reliably even in muddy or irregular bore walls. Solution: Geared linkage driven by two synchronized DC motors ensures sufficient torque to overcome soil resistance.",
      imageUrl: fabricationImage,
    },
    {
      id: "fab-3",
      order: 3,
      title: "Long-Distance RS-485 Communication over Ethernet Cable",
      phase: "Phase 3: Long-Distance Umbilical Tether",
      summary: "Implemented the industrial RS-485 differential communication method over standard 8-core Ethernet cable (Cat5e/Cat6) to eliminate signal loss over long underground distances.",
      materials: [
        "MAX485 Differential Bus Transceiver modules (Ground & Robot nodes)",
        "Standard 8-Core Shielded Cat5e / Cat6 Twisted Pair Ethernet Cable (50m reel)",
        "RJ45 terminal breakout blocks & strain relief connectors",
        "120 Ohm termination resistors to prevent signal reflections"
      ],
      tools: [
        "Ethernet cable crimper & cable continuity tester",
        "Digital storage oscilloscope for differential eye-diagram analysis"
      ],
      engineeringProcess: "Because borewells descend 30 to 40+ meters into the earth, standard TTL UART signals suffer severe attenuation, voltage drops, and high electromagnetic interference from motor switching. To overcome this long underground distance, we implemented the RS-485 industrial protocol. By transmitting differential voltage signals (+2V to +6V differential across the twisted pairs in a standard Ethernet cable), any noise induced affects both wires equally and is eliminated by common-mode rejection. The Ethernet cable's remaining twisted pairs carry logic ground, analog video, and 1-way voice lines.",
      challengesAndSolutions: "Challenge: Signal reflections and packet drop over long coils of cable. Solution: Installed 120Ω terminating resistors at both the Ground Unit and Robot Unit ends, ensuring flawless command response at 9600/19200 baud.",
      imageUrl: fabricationImage,
    },
    {
      id: "fab-4",
      order: 4,
      title: "Arduino Mega C++ Controller & 8-Channel Relay Module",
      phase: "Phase 4: Electronics & Firmware",
      summary: "Programmed an Arduino Mega in C++ to manage the 8-relay module and drive all 4 DC motors bidirectionally.",
      materials: [
        "Arduino Mega (ATmega2560) microcontroller",
        "8-Channel 5V/12V Optocoupler-isolated Relay Module",
        "MAX485 communication transceiver",
        "Status LED indicators & flyback protection diodes"
      ],
      tools: [
        "Arduino IDE (C++ programming)",
        "Digital multimeter & soldering station",
        "Oscilloscope for relay timing validation"
      ],
      engineeringProcess: "The entire robot actuation is managed by an Arduino Mega running structured C++ code. The 8-relay board acts as 4 independent H-bridge controllers: Relay 1 & 2 control Motor 1 (Claw), Relay 3 & 4 control Motor 2 (Foldable arm A), Relay 5 & 6 control Motor 3 (Foldable arm B), and Relay 7 & 8 control Motor 4. The firmware continuously parses commands from the RS-485 bus and outputs status telemetry back to the ground screen.",
      challengesAndSolutions: "Challenge: Inductive motor kickback causing MCU resets. Solution: Added optocoupler isolation, flyback diodes across all motor terminals, and separate power filtering for the Arduino Mega logic rail.",
      imageUrl: fabricationImage,
    },
    {
      id: "fab-5",
      order: 5,
      title: "Ground Unit Control Panel & Real-Time Status Display",
      phase: "Phase 5: Surface Operator Console",
      summary: "Constructed the ground control panel featuring an RS-485 master link and a real-time display screen showing which motors are moving forward or backward.",
      materials: [
        "Ergonomic ground console enclosure with Ethernet tether port",
        "Real-time LCD status display screen",
        "Heavy-duty directional toggle switches for Motor 1–4",
        "12V 8Ah battery compartment and voltmeter"
      ],
      tools: [
        "Wiring crimpers & panel punch tools",
        "Ground test simulation rig"
      ],
      engineeringProcess: "At the surface, the rescue operator needs clear, instantaneous feedback. The Ground Unit console features dedicated forward/stop/backward switches for each motor, accompanied by a digital display that clearly shows the real-time operational status: e.g., 'Motor 1: FORWARD (Grabbing)', 'Motor 2&3: FORWARD (Opening Base Support)', etc. This eliminates operator confusion during high-stress rescue operations.",
      challengesAndSolutions: "Challenge: Knowing if a motor is actually active deep underground. Solution: The ground unit tracks the relay states and displays direction and RS-485 packet confirmation on the screen in real time.",
      imageUrl: groundUnitImage,
    },
  ],
  robotFunctions: [
    {
      id: "func-1",
      order: 1,
      title: "Main Chest Gripping Mechanism",
      subsystem: "Robot Unit / Primary Extraction",
      iconName: "ShieldCheck",
      shortDescription: "DC motor driven mechanical claw that grabs the child's chest safely.",
      howItWorks: "The robot descends vertically until the inspection camera confirms the child's chest position. The operator activates Motor 1 on the Ground Unit. Relay 1 energizes to drive the motor forward, gently closing the claw around the child's upper body. Relay 2 allows reverse movement to release or adjust the grip if needed.",
      technicalSpecs: [
        { label: "Actuator", value: "High-Torque 12V DC Gear Motor" },
        { label: "Relay Control", value: "Relay 1 (Forward/Grip) & Relay 2 (Backward/Open)" },
        { label: "Contact Area", value: "Padded anatomical chest curves" },
        { label: "Holding Capacity", value: "Up to 25 kg payload" }
      ],
      safetyFailSafe: "Relays configured with interlocking logic in C++ code so forward and backward can never energize simultaneously.",
      imageUrl: robotHeroImage,
      stepInRescueSequence: 1,
    },
    {
      id: "func-2",
      order: 2,
      title: "Extra Foldable Base Leg Support",
      subsystem: "Robot Unit / Secondary Bottom Support",
      iconName: "Anchor",
      shortDescription: "2 DC motors unfold bottom support arms under the child's feet/legs to prevent falling.",
      howItWorks: "After the robot reaches past the child's position, the operator engages Motor 2 and Motor 3 from the Ground Unit. Controlled by Relays 3 to 6, these two motors rotate the foldable support arms outward. The arms lock in place beneath the child's legs, forming a solid base platform so that even if the child shifts, they are firmly supported from beneath.",
      technicalSpecs: [
        { label: "Actuation Motors", value: "2 DC Geared Motors (Motors 2 & 3)" },
        { label: "Relay Control", value: "Relays 3 & 4 (Motor 2) and Relays 5 & 6 (Motor 3)" },
        { label: "Deployment Angle", value: "0° (Folded) to 90° (Expanded Base Support)" },
        { label: "Purpose", value: "Under-body safety cradle preventing slip" }
      ],
      safetyFailSafe: "Mechanical travel limits prevent the foldable arms from exceeding maximum borewell diameter.",
      imageUrl: fabricationImage,
      stepInRescueSequence: 2,
    },
    {
      id: "func-3",
      order: 3,
      title: "Long-Distance RS-485 Communication over Ethernet Cable",
      subsystem: "Ground-to-Robot Umbilical Link",
      iconName: "Radio",
      shortDescription: "RS-485 serial communication over standard 8-core Ethernet cable for noise-free command transmission deep underground.",
      howItWorks: "Because borewells represent long distances underground (up to 40-50m or more), standard low-voltage logic suffers massive attenuation and noise from electric motors. BOTNIX incorporates the industrial RS-485 differential communication method using standard Cat5e/Cat6 8-core twisted pair Ethernet cable. Using MAX485 transceivers, commands sent from the Ground Unit switches and telemetry returned to the real-time display travel across differential A and B lines with 100% noise rejection and negligible packet loss.",
      technicalSpecs: [
        { label: "Protocol", value: "RS-485 Industrial Serial (EIA/TIA-485)" },
        { label: "Physical Medium", value: "Standard 8-Core Cat5e / Cat6 Ethernet Cable" },
        { label: "Transceiver", value: "MAX485 Differential Bus Transceivers" },
        { label: "Transmission Distance", value: "Rated up to 1,200 meters (Tested at 40m+ shaft depth)" },
        { label: "Noise Immunity", value: "Common-Mode Differential Rejection" }
      ],
      safetyFailSafe: "Heartbeat checksum packet verification: if Ethernet cable is severed, downhole motors automatically shut down safely.",
      imageUrl: fabricationImage,
      stepInRescueSequence: 3,
    },
    {
      id: "func-4",
      order: 4,
      title: "Ground Unit Real-Time Status Display Screen",
      subsystem: "Ground Unit / Telemetry & Monitoring",
      iconName: "Cpu",
      shortDescription: "Displays live status of all 4 motors and relays (Forward, Backward, Stop).",
      howItWorks: "The Ground Unit features a real-time digital display panel connected to the Arduino Mega via the RS-485 bus. Whenever the operator flips a switch, the screen immediately shows which motor is running (Motor 1, Motor 2, Motor 3, Motor 4) and which direction it is turning (Forward or Backward). This gives the rescuer 100% certainty of the robot's physical configuration deep underground.",
      technicalSpecs: [
        { label: "Display Type", value: "High-contrast LCD / OLED Screen" },
        { label: "Tracked Motors", value: "Motor 1 (Claw), Motor 2 & 3 (Base Support), Motor 4" },
        { label: "Direction States", value: "Forward [FWD], Backward [BWD], Stopped [OFF]" },
        { label: "Relay Mapping", value: "Visual 8-Relay ON/OFF Status Grid" }
      ],
      safetyFailSafe: "Emergency Stop switch instantly cuts power to all 8 relays, bringing all 4 motors to a dead halt.",
      imageUrl: groundUnitImage,
      stepInRescueSequence: 4,
    },
    {
      id: "func-5",
      order: 5,
      title: "Live Camera & One-Way Voice Communication",
      subsystem: "Robot Unit / Vision & Audio",
      iconName: "Camera",
      shortDescription: "Camera visual feed and surface-to-borewell voice speaker to calm the trapped child.",
      howItWorks: "A wide-angle camera with high-intensity LEDs transmits live video to the ground monitor so rescuers can inspect the shaft. A one-way audio communication channel allows rescuers or parents at the surface to speak soothing words down into the borewell through the robot's onboard speaker, keeping the child calm and still.",
      technicalSpecs: [
        { label: "Camera", value: "Wide-Angle Low-Light Video Camera" },
        { label: "Illumination", value: "Bright LED Array" },
        { label: "Voice Method", value: "Surface Mic to Downhole Loudspeaker (1-Way Audio)" },
        { label: "Functionality", value: "Active & functional for rescue operations" }
      ],
      safetyFailSafe: "Audio volume limiter prevents acoustic overload in the narrow confined borewell echo chamber.",
      stepInRescueSequence: 5,
    },
    {
      id: "func-6",
      order: 6,
      title: "Continuous Oxygen Supply & 12V 8Ah Power Support",
      subsystem: "Robot Unit / Life Support & Power",
      iconName: "Wind",
      shortDescription: "Delivers fresh oxygen to the trapped child in hypoxic depths with 20-30 min battery life.",
      howItWorks: "Deep borewells quickly run out of oxygen and accumulate dangerous CO2 and gases. A dedicated flexible silicone oxygen hose attached to the tether line continuously pumps fresh oxygen directly to the victim's face and chest as soon as the robot enters the borewell. The system is sustained by a 12V 8Ah heavy-duty battery.",
      technicalSpecs: [
        { label: "Supply Tube", value: "Kink-resistant silicone air conduit" },
        { label: "Source", value: "Medical Oxygen Cylinder / Surface Air Blower" },
        { label: "Target Depth", value: "Up to 40 meters" },
        { label: "Battery Spec", value: "12V 8Ah High-Discharge (20-30 min runtime)" }
      ],
      safetyFailSafe: "One-way anti-backflow check valve prevents dust or borehole water from entering the oxygen line.",
      stepInRescueSequence: 6,
    },
  ],
  writtenReport: {
    abstract: "Accidental falls of small children into abandoned, uncapped borewells present a severe humanitarian emergency in rural and agricultural regions across Bangladesh and South Asia. Borewells typically range between 6 and 14 inches (150 mm to 350 mm) in diameter and extend up to 40 meters deep, making human entry physically impossible. Traditional excavation of an adjacent parallel shaft requires days of heavy machinery work, during which trapped children frequently perish from asphyxiation, hypothermia, or shock. This report introduces the BOTNIX Borewell Rescue Robot, developed by Team BOTNIX representing Bangladesh in the 2026 International Robotics Championship in Malaysia. The BOTNIX system implements a two-unit architecture: an in-borewell Robot Unit and a surface Ground Unit, communicating over long underground distances via an industrial RS-485 serial communication protocol running through a standard 8-core Ethernet cable (Cat5e/Cat6). The Robot Unit features a high-torque DC motor driven chest claw to gently secure the child's torso, supplemented by a secondary foldable base support mechanism actuated by two DC motors that open beneath the child's legs to prevent slippage. The entire system is orchestrated by an Arduino Mega microcontroller programmed in C++, operating an 8-channel relay module configured as four H-bridge motor drivers (one relay for forward, one for backward per motor). Visual navigation is provided by an illuminated camera, while a one-way voice communication system allows rescuers to calm the child and an oxygen tube delivers vital life-support. The Ground Unit provides an intuitive operator panel with a real-time status display showing the active state and direction of all four motors. Powered by a 12V 8Ah battery delivering 20–30 minutes of operational backup, the BOTNIX robot offers a rapid, reliable, and deployable solution for saving young lives.",
    problemStatement: "Abandoned irrigation borewells throughout developing nations represent lethal vertical pitfall traps. Because diameters rarely exceed 14 inches, adult rescue personnel cannot descend. Victims are exposed to hypoxic atmospheric conditions (rapid oxygen depletion below 10 meters depth), complete darkness, cold, and intense panic. Previous improvised robotic attempts have failed due to three major limitations: 1) Lack of bottom support (causing the victim to slip when grabbed by the arms); 2) Severe electrical signal degradation and noise when transmitting simple logic down 40-meter underground depths; and 3) Rigid claws that inflict severe skeletal trauma. The BOTNIX project addresses these engineering challenges with a dual-securing approach (chest claw + foldable bottom foot support) tied together with an industrial RS-485 differential bus running over affordable, rugged Cat5e Ethernet cable.",
    designMethodology: "The BOTNIX Borewell Rescue Robot was engineered according to strict field constraints: 1) Maximum outer diameter of under 150 mm in collapsed state to fit narrow borewell casings; 2) Dual-support philosophy where the child is supported both at the chest and from the base; 3) Modular two-unit separation between downhole actuation (Robot Unit) and surface control (Ground Unit); 4) Long-distance communication reliability using RS-485 differential transceivers over standard 8-core Cat5e/Cat6 Ethernet cable; 5) High reliability electrical switching using an 8-channel relay module rather than sensitive unshielded semiconductor drivers; 6) Embedded C++ firmware running on an Arduino Mega for deterministic real-time control; and 7) Self-contained 12V 8Ah DC power giving 20 to 30 minutes of mission battery life.",
    mechanicalDesign: "The mechanical system is segmented into the upper chest grab claw and the lower foldable leg cradle. The upper claw is driven by Motor 1, utilizing a lead-screw or high-torque linkage to close padded curved fingers around the child's torso. The lower support consists of two articulated arms tucked flush against the cylindrical chassis during descent. Once the robot reaches past the child's legs, Motors 2 and 3 activate to expand the arms outwards at a 90-degree angle, forming a protective cradle beneath the child's feet. The robot is lowered and hoisted through the borewell shaft manually by hand or using a mechanical pulley tether, providing the operator with direct tactile feedback.",
    electricalAndSensory: "The electrical system is controlled by an Arduino Mega (ATmega2560) running custom C++ code. The 4 DC motors are driven by an 8-channel optoisolated relay module. Each motor is assigned two relays: the first relay switches positive polarity for Forward motion (e.g. closing claw or opening foldable support), while the second relay switches reverse polarity for Backward motion (opening claw or folding support). When neither relay is energized, the motor is grounded and stopped. To bridge the long vertical distance between the surface Ground Unit and the deep downhole Robot Unit, an RS-485 differential bus (utilizing MAX485 transceivers) communicates serial command packets and telemetry over a standard 8-core Cat5e Ethernet cable. The twisted pairs reject electromagnetic noise from the motors, ensuring error-free communication across 40+ meters. Power is supplied by a 12V 8Ah rechargeable battery pack yielding 20 to 30 minutes of continuous rescue backup. For sensor feedback, an illuminated camera sends real-time video to the ground station, while a one-way audio line conveys the rescuer's voice down to an onboard speaker.",
    workingPrinciple: "The rescue operation executes in 5 sequential steps: 1) Initial Deployment: The robot unit is aligned over the borewell mouth and lowered manually via tether line while the oxygen tube supplies continuous fresh air and the RS-485 link establishes connectivity; 2) Visual Verification: The camera spots the child; the rescuer speaks through the one-way audio system to reassure the child; 3) Chest Securing: The operator flips the Motor 1 switch; RS-485 sends the command and Relay 1 closes to drive Motor 1 forward, securing the main claw around the child's chest; 4) Base Support Deployment: Motors 2 and 3 are engaged via Relays 3 and 5, opening the foldable bottom support arms beneath the child's legs; 5) Controlled Retrieval: With both chest and base securely held and real-time confirmation showing on the Ground Unit display, the robot and child are smoothly lifted to the surface.",
    safetyAndFailSafes: "Safety is critical during pediatric confined-space rescue: 1) RS-485 Heartbeat & CRC Check: Continuous packet verification ensures that if the Ethernet cable is severed or damaged, all downhole motors fail-safe into a locked stopped state; 2) Software Interlock: The C++ code prevents simultaneous activation of forward and backward relays on any motor, eliminating short-circuit risk; 3) Dual-Level Hold: Combining chest claw and bottom leg support prevents any possibility of the child slipping downwards; 4) Emergency Stop: Master disconnect cut-off on the Ground Unit instantly drops power to all 8 relays; 5) Power Autonomy: The 12V 8Ah battery operates completely independently of erratic municipal grid power for over 20–25 minutes; 6) Padded Contact: All claws and folding supports are lined with medical-grade cushioning.",
    fieldTestResults: "Testing conducted in a vertical simulated borewell pipe structure verified reliable deployment: The RS-485 communication link over 50 meters of coiled Cat5e Ethernet cable maintained 0% packet loss at 9600 and 19200 baud under heavy inductive motor switching noise. Motor 1 achieved full chest grab clamping in 3.8 seconds with safe, non-injurious holding force. Motors 2 and 3 opened the foldable base support arms in 4.2 seconds, successfully supporting simulated test payloads of up to 25 kg. The 8-channel relay module executed over 100 consecutive forward/backward cycles without failure or relay contact sticking. The Ground Unit display accurately reported active motor states with zero latency. The 12V 8Ah battery provided 24 minutes of heavy cyclic actuation before reaching low-voltage cutoff threshold.",
    conclusionAndMalaysiaGoals: "The BOTNIX Borewell Rescue Robot demonstrates an effective, low-cost, and life-saving mechatronic solution to an urgent humanitarian challenge. By combining an Arduino Mega C++ controller, an RS-485 serial communication system over standard Ethernet cable, an 8-relay 4-motor architecture, a chest grab claw, and a 2-motor foldable leg support, BOTNIX provides unparalleled safety during vertical shaft extractions. Representing Bangladesh at the 2026 International Robotics Championship in Malaysia, Team BOTNIX aims to showcase this functional prototype to global judges, refine the system into two-way communication, and promote rapid-deployment rescue technology for emergency services worldwide.",
    billOfMaterials: [
      { id: "bom-1", item: "Main Chest Claw & Linkage", specification: "CNC aluminum curved arms with protective rubber padding", quantity: 1, costEstimateUSD: 45, purpose: "Primary torso grabbing" },
      { id: "bom-2", item: "Foldable Base Support Arms", specification: "Dual folding aluminum support linkages with pivot hinges", quantity: 1, costEstimateUSD: 40, purpose: "Bottom support beneath child's legs" },
      { id: "bom-3", item: "High-Torque DC Gear Motors", specification: "12V High-Torque DC Geared Motors (120 RPM, 15 kg-cm)", quantity: 4, costEstimateUSD: 60, purpose: "Actuation for claw (1) and foldable arms (2), auxiliary (1)" },
      { id: "bom-4", item: "RS-485 Transceiver Modules (MAX485)", specification: "Differential bus transceiver IC modules with 120Ω termination", quantity: 2, costEstimateUSD: 8, purpose: "Noise-free long-distance communication between Ground and Robot" },
      { id: "bom-5", item: "Cat5e / Cat6 Shielded Ethernet Cable", specification: "8-Core Twisted Pair Cable (50 meters spool with RJ45)", quantity: 1, costEstimateUSD: 25, purpose: "Long-distance downhole umbilical communication tether" },
      { id: "bom-6", item: "8-Channel Relay Module", specification: "8-Channel 5V/12V optocoupler isolated relay board", quantity: 1, costEstimateUSD: 14, purpose: "Forward & backward polarity control for 4 motors" },
      { id: "bom-7", item: "Microcontroller Board", specification: "Arduino Mega 2560 R3 (ATmega2560)", quantity: 1, costEstimateUSD: 22, purpose: "Main brain running C++ control firmware" },
      { id: "bom-8", item: "Rechargeable Power Battery", specification: "12V 8Ah Heavy-Duty Rechargeable Battery", quantity: 1, costEstimateUSD: 35, purpose: "20–30 minute mission power backup" },
      { id: "bom-9", item: "Ground Unit Status Display Screen", specification: "Real-time LCD / OLED Display module", quantity: 1, costEstimateUSD: 16, purpose: "Live display of Motor 1, 2, 3, 4 FWD/BWD states" },
      { id: "bom-10", item: "Ground Unit Operator Control Panel", specification: "Rugged panel with multi-directional toggle switches", quantity: 1, costEstimateUSD: 28, purpose: "Surface rescuer manual control interface" },
      { id: "bom-11", item: "Inspection Camera & LED Illumination", specification: "Wide-angle low-light camera with 12V LED ring", quantity: 1, costEstimateUSD: 32, purpose: "Borewell shaft visual guidance" },
      { id: "bom-12", item: "One-Way Voice Communication System", specification: "Surface microphone linked to downhole audio speaker", quantity: 1, costEstimateUSD: 18, purpose: "Surface voice reassurance for trapped child" },
      { id: "bom-13", item: "Oxygen Delivery Conduit Tube", specification: "Medical grade flexible silicone air hose (40m)", quantity: 1, costEstimateUSD: 20, purpose: "Fresh oxygen supply to victim" },
      { id: "bom-14", item: "Tether Cable & Manual Pulley Harness", specification: "High-tensile load tether with swivel hook", quantity: 1, costEstimateUSD: 30, purpose: "Vertical lifting/lowering support" },
    ]
  },
  lastUpdated: new Date().toISOString(),
};
